/* Each call must fail before a backend result becomes visible. */
static const char* numerical_invalids[] = {
    "nt_linear()", "nt_linear(w, b, x, 2)", "nt_linear(w, b, x, 2, 2, 1)",
    "nt_linear('w', b, x, 2, 2)", "nt_linear(w, 1, x, 2, 2)",
    "nt_linear(w, b, list_new(), 2, 2)", "nt_linear(w, b, x, '2', 2)",
    "nt_linear(w, b, x, 0, 2)", "nt_linear(w, b, x, 2, -1)",
    "nt_linear(w, b, x, 2.5, 2)", "nt_linear(w, b, x, 2, 1e39)",
    "nt_linear(w, b, x, 1048576, 1048576)", "nt_linear(w, b, x, 1, 2)",
    "nt_linear(w, [0], x, 2, 2)", "nt_linear(w, b, [1], 2, 2)",
    "nt_linear([1e39, 2, 3, 4], b, x, 2, 2)",
    "nt_linear(w, nan_array, x, 2, 2)",
    "nt_linear_vjp(w, x, b, 2)", "nt_linear_vjp(w, x, 1, 2, 2)",
    "nt_linear_vjp(w, x, b, 2, 0)", "nt_linear_vjp(w, x, [1], 2, 2)",
    "nt_linear_vjp(w, [1e39, 0], b, 2, 2)",
    "nt_tanh()", "nt_tanh(x, 1)", "nt_tanh(1)", "nt_tanh('x')",
    "nt_tanh(map_new())", "nt_tanh([1e39])", "nt_tanh(nan_array)",
    "nt_tanh_vjp(x)", "nt_tanh_vjp(x, b, 1)", "nt_tanh_vjp(x, 1)",
    "nt_tanh_vjp([0], b)", "nt_tanh_vjp([1.01, 0], b)",
    "nt_tanh_vjp([-1.01, 0], b)", "nt_tanh_vjp([0, 0], [1, 1e39])",
    "nt_mse_grad(x)", "nt_mse_grad(x, b, 1)", "nt_mse_grad(x, [0])",
    "nt_mse_grad(x, 'target')", "nt_mse_grad([1e39], [0])",
    "nt_mse_grad(x, nan_array)",
    "nt_sgd(x, b)", "nt_sgd(x, b, 0.1, 1)", "nt_sgd(x, [1], 0.1)",
    "nt_sgd(x, b, 'rate')", "nt_sgd(x, b, -0.1)", "nt_sgd(x, b, 1e39)",
    "nt_sgd(x, [0, 1e39], 0)", "nt_sgd(1, b, 0.1)",
    "rng_normal(rng)", "rng_normal(rng, 1, 1)", "rng_normal(1, 1)",
    "rng_normal(map_new(), 1)", "rng_normal(rng, 0)", "rng_normal(rng, -1)",
    "rng_normal(rng, 1.5)", "rng_normal(rng, 1048577)",
    "rng_normal(rng, 1e39)", "rng_normal(rng, 'n')",
    "isfinite()", "isfinite(1, 2)", "isfinite('x')", "isfinite([1])",
    "isfinite(map_new())", "isfinite(list_new())",
    "def nt_linear(w, b, x, r, c):\n    return w\n",
    "def NT_TANH(x):\n    return x\n",
    "def nt_linear_vjp(w, x, dy, r, c):\n    return w\n",
    "def nt_tanh_vjp(y, dy):\n    return y\n",
    "def nt_mse_grad(p, t):\n    return p\n",
    "def nt_sgd(p, g, lr):\n    return p\n",
    "def rng_normal(state, n):\n    return n\n",
    "def isfinite(value):\n    return value\n",
};
