#!/usr/bin/env python3
"""Emit numerical_vectors.aml using scalar equations and Python's standard library.

Fixture authoring only: no Python dependency is needed to run the committed gate.
Every AML input is rounded to binary32 before its independent expected value is
calculated. Tolerances admit normal libm/float accumulation differences.
"""

import math
import struct


def f32(value):
    return struct.unpack("<f", struct.pack("<f", value))[0]


def literal(values):
    return "[" + ", ".join(format(f32(x), ".9g") for x in values) + "]"


def array(name, values):
    line = f"{name} = {literal(values)}"
    if len(line) <= 240:
        print(line)
    else:
        print(f"{name} = zeros({len(values)})")
        for i, value in enumerate(values):
            print(f"{name}[{i}] = {f32(value):.9g}")


def check(name, values, label, tolerance=4e-6):
    print(f'assert(len({name}) == {len(values)}, "{label} length")')
    for i, value in enumerate(values):
        tol = max(tolerance, abs(value) * tolerance)
        print(f'assert(abs({name}[{i}] - {f32(value):.9g}) <= {tol:.9g}, "{label} {i}")')


def linear(w, b, x, rows, cols):
    return [f32(b[r] + sum(w[r * cols + c] * x[c] for c in range(cols)))
            for r in range(rows)]


def vjp(w, x, dy, rows, cols):
    return ([f32(dy[r] * x[c]) for r in range(rows) for c in range(cols)]
            + dy[:]
            + [f32(sum(w[r * cols + c] * dy[r] for r in range(rows)))
               for c in range(cols)])


def mse(pred, target):
    residual = [p - t for p, t in zip(pred, target)]
    return [f32(sum(x * x for x in residual) / len(pred))] + [
        f32(2 * x / len(pred)) for x in residual]


class Stream:
    def __init__(self, seed):
        self.state = 0
        self.word()
        self.state = (self.state + seed) & ((1 << 64) - 1)
        self.word()

    def word(self):
        old = self.state
        self.state = (old * 6364136223846793005 + 109) & ((1 << 64) - 1)
        shift = (((old >> 18) ^ old) >> 27) & ((1 << 32) - 1)
        rotate = old >> 59
        return ((shift >> rotate) | (shift << ((-rotate) & 31))) & ((1 << 32) - 1)

    def normals(self, n):
        result = []
        for _ in range(n):
            u1 = (self.word() + 1.0) / 4294967297.0
            u2 = self.word() / 4294967296.0
            result.append(f32(math.sqrt(-2 * math.log(u1)) * math.cos(2 * math.pi * u2)))
        return result


def check_state(name, state):
    for limb in range(4):
        expected = (state >> (16 * limb)) & 65535
        print(f'assert(map_get({name}, "state{limb}") == {expected}, "normal state limb {limb}")')


print("# Generated by tests/numerical_reference.py; independent scalar equations.")
for case, (rows, cols) in enumerate(((1, 1), (2, 3), (3, 2), (4, 5))):
    w = [f32(((i * 7 + case * 3) % 17 - 8) / 13) for i in range(rows * cols)]
    b = [f32((i - 2) / 7) for i in range(rows)]
    x = [f32((i * 3 - 4) / 11) for i in range(cols)]
    dy = [f32((i - 1) / 5) for i in range(rows)]
    array("w", w); array("b", b); array("x", x); array("dy", dy)
    print(f"y = nt_linear(w, b, x, {rows}, {cols})")
    check("y", linear(w, b, x, rows, cols), f"linear {case}")
    print(f"g = nt_linear_vjp(w, x, dy, {rows}, {cols})")
    check("g", vjp(w, x, dy, rows, cols), f"linear vjp {case}")
    check("w", w, f"weights unchanged {case}")
    check("b", b, f"bias unchanged {case}")
    check("x", x, f"input unchanged {case}")
    check("dy", dy, f"upstream unchanged {case}")

values = [-100, -9, -2, -0.5, 0, 0.125, 0.5, 2, 9, 100]
dy = [f32((i - 4) / 7) for i in range(len(values))]
y = [f32(math.tanh(x)) for x in values]
array("x", values); array("dy", dy)
print("y = nt_tanh(x)")
check("y", y, "tanh", 2e-7)
print("g = nt_tanh_vjp(y, dy)")
check("g", [f32(d * (1 - value * value)) for value, d in zip(y, dy)], "tanh vjp")
print("again = nt_tanh(x)\ny[0] = 99")
check("again", y, "fresh tanh output", 2e-7)
check("x", values, "tanh input unchanged")

for case, (pred, target) in enumerate((([1], [-1]),
                                      ([1, 2, -3], [0.5, 2.5, 1]),
                                      ([0.1, -0.3, 0.7, 0.9], [0.2, -0.1, 0.4, 1]))):
    pred = [f32(x) for x in pred]; target = [f32(x) for x in target]
    array("pred", pred); array("target", target)
    print("loss = nt_mse_grad(pred, target)")
    expected = mse(pred, target)
    check("loss", expected, f"mse {case}")
    array("grad", expected[1:])
    print("updated = nt_sgd(pred, grad, 0.125)")
    check("updated", [f32(p - 0.125 * g) for p, g in zip(pred, expected[1:])], f"sgd {case}")
    check("pred", pred, f"sgd input unchanged {case}")
    print("idle = nt_sgd(pred, grad, 0)")
    check("idle", pred, f"zero rate {case}")

# Follow twelve explicit learning steps; each update consumes the previous
# step's state and every reverse derivative is checked before SGD.
w = [f32(0.2), f32(-0.3), f32(0.4), f32(0.1)]
b = [f32(0.05), f32(-0.1)]
x = [f32(0.7), f32(-0.2)]
target = [f32(0.3), f32(-0.5)]
array("w", w); array("b", b); array("x", x); array("target", target)
for step in range(12):
    z = linear(w, b, x, 2, 2)
    y = [f32(math.tanh(z_i)) for z_i in z]
    loss = mse(y, target)
    dz = [f32(d * (1 - y_i * y_i)) for y_i, d in zip(y, loss[1:])]
    grads = vjp(w, x, dz, 2, 2)
    print("z = nt_linear(w, b, x, 2, 2)\ny = nt_tanh(z)\nloss = nt_mse_grad(y, target)")
    check("loss", loss, f"trajectory loss {step}")
    print("dy = zeros(2)\ndy[0] = loss[1]\ndy[1] = loss[2]\ndz = nt_tanh_vjp(y, dy)\ng = nt_linear_vjp(w, x, dz, 2, 2)")
    check("g", grads, f"trajectory vjp {step}")
    print("dw = zeros(4)\ndw[0] = g[0]\ndw[1] = g[1]\ndw[2] = g[2]\ndw[3] = g[3]")
    print("db = zeros(2)\ndb[0] = g[4]\ndb[1] = g[5]")
    print("w = nt_sgd(w, dw, 0.125)\nb = nt_sgd(b, db, 0.125)")
    w = [f32(a - 0.125 * d) for a, d in zip(w, grads[:4])]
    b = [f32(a - 0.125 * d) for a, d in zip(b, grads[4:6])]
    check("w", w, f"trajectory weights {step}")
    check("b", b, f"trajectory bias {step}")

for seed in (0, 1, 42, 16777215):
    stream = Stream(seed)
    print(f"rng = rng_new({seed})\ncopy = rng\na = rng_normal(rng, 3)")
    check("a", stream.normals(3), f"normal seed {seed} first", 3e-7)
    check_state("rng", stream.state)
    print("b = rng_normal(rng, 4)")
    check("b", stream.normals(4), f"normal seed {seed} second", 3e-7)
    check_state("rng", stream.state)
    print("whole = rng_normal(copy, 7)")
    check("whole", Stream(seed).normals(7), f"normal seed {seed} batch", 3e-7)
    check_state("copy", stream.state)
    next_value = (stream.word() >> 8) / (1 << 24)
    print(f'assert(rng_uniform(rng) == {next_value:.17g}, "normal exact word consumption")')

print('assert(isfinite(0) == 1, "finite zero")')
print('assert(isfinite(3.4e38) == 1, "finite large")')
print('assert(isfinite(1e39) == 0, "positive infinity")')
print('assert(isfinite(-1e39) == 0, "negative infinity")')
print('assert(isfinite(1e39 - 1e39) == 0, "not a number")')
print('PRINT "AML_NUMERICAL_VECTORS_OK"')
