#!/usr/bin/env python3
"""Regenerate sampling_vectors.aml with Python integer arithmetic only.

This is a fixture-authoring tool, not a dependency of make test-sampling.
The seed-42 stream is anchored to the published PCG32 stream-54 vector.
"""

MASK64 = (1 << 64) - 1
MASK32 = (1 << 32) - 1


class Reference:
    def __init__(self, seed):
        self.state = 0
        self.u32()
        self.state = (self.state + seed) & MASK64
        self.u32()

    def u32(self):
        old = self.state
        self.state = (old * 6364136223846793005 + 109) & MASK64
        shift = (((old >> 18) ^ old) >> 27) & MASK32
        rotate = old >> 59
        return ((shift >> rotate) | (shift << ((-rotate) & 31))) & MASK32

    def uniform(self):
        return (self.u32() >> 8) / (1 << 24)

    def index(self, bound):
        threshold = (1 << 32) % bound
        while True:
            value = self.u32()
            if value >= threshold:
                return value % bound


known = Reference(42)
assert [known.u32() for _ in range(6)] == [
    0xA15C02B7, 0x7B47F409, 0xBA1D3330,
    0x83D2F293, 0xBFA4784B, 0xCBED606E,
]


def emit_state(name, state):
    print(f'assert(map_get({name}, "algorithm") == 1, "algorithm tag")')
    for limb in range(4):
        value = (state >> (16 * limb)) & 65535
        print(f'assert(map_get({name}, "state{limb}") == {value}, "state limb {limb}")')


print('# Generated by tests/sampling_reference.py; exact PCG32 integer oracle.')
for seed in (0, 1, 42, 16777215):
    reference = Reference(seed)
    print(f'rng = rng_new({seed})')
    emit_state('rng', reference.state)
    for i in range(6):
        value = reference.uniform()
        print(f'assert(rng_uniform(rng) == {value:.17g}, "seed {seed} uniform {i}")')
    for bound in (1, 3, 7, 16777216, 10000, 1):
        value = reference.index(bound)
        print(f'assert(rng_index(rng, {bound}) == {value}, "seed {seed} bound {bound}")')
    emit_state('rng', reference.state)

# The two zero outputs at states 0 and 109 must both be rejected for bound 3.
reference = Reference(0)
reference.state = 0
print('rng = rng_new(0)')
for limb in range(4):
    print(f'map_set(rng, "state{limb}", 0)')
print(f'assert(rng_index(rng, 3) == {reference.index(3)}, "bounded rejection")')
emit_state('rng', reference.state)

print('''
def identity(stream):
    return stream
def advance(stream):
    return rng_uniform(stream)
first = rng_new(42)
bare = first
parenthesized = (first)
returned = identity(first)
assert(rng_uniform(first) == rng_uniform(bare), "bare copy")
assert(rng_uniform(parenthesized) == rng_uniform(returned), "expression copies")
assert(advance(first) == rng_uniform(bare), "parameter shares caller stream")
assert(advance(first) == rng_uniform(bare), "parameter advances caller")
assert(rng_uniform(parenthesized) == rng_uniform(returned), "copies remain independent")
assert(rng_index(first, 1) == 0, "singleton index")
assert(rng_uniform(bare) >= 0, "consume singleton peer draw")
assert(text_equal(list_key(map_keys(first)), list_key(map_keys(bare))), "state key order")
assert(map_get(first, "state0") == map_get(bare, "state0"), "singleton consumes draw")
assert(map_get(first, "state1") == map_get(bare, "state1"), "singleton consumes draw")
assert(map_get(first, "state2") == map_get(bare, "state2"), "singleton consumes draw")
assert(map_get(first, "state3") == map_get(bare, "state3"), "singleton consumes draw")
weights = [0, 1, 0]
assert(categorical_at(weights, 1, 0) == 1, "zero weights at left edge")
assert(categorical_at(weights, 1, 0.99999994) == 1, "zero weights at right edge")
weights = [1, 3]
assert(categorical_at(weights, 1, 0.24999999) == 0, "below CDF boundary")
assert(categorical_at(weights, 1, 0.25) == 1, "strict CDF boundary")
assert(categorical_at(weights, 0.5, 0.05) == 0, "temperature square left")
assert(categorical_at(weights, 0.5, 0.25) == 1, "temperature square right")
assert(categorical_at(weights, 0.000001, 0) == 1, "cold stable maximum")
extreme = [1e-38, 3e38]
assert(categorical_at(extreme, 0.000001, 0.99999994) == 1, "extreme finite weights")
assert(categorical_at(extreme, 3e38, 0.25) == 0, "hot weights approach uniform")
assert(categorical_at(extreme, 3e38, 0.75) == 1, "hot weights second half")
first = rng_new(42)
bare = first
assert(rng_categorical(first, [0, 1, 0], 1) == 1, "native categorical")
assert(rng_uniform(bare) >= 0, "consume categorical peer draw")
assert(rng_uniform(first) == rng_uniform(bare), "categorical advances exactly once")
assert(weights[0] == 1, "weights unchanged")
assert(weights[1] == 3, "weights unchanged")
PRINT "AML_SAMPLING_VECTORS_OK"
'''.strip())
