#!/usr/bin/env python3
"""Freeze Python 3.12 / Unicode 15 classification and line-input examples.

Run with --write to regenerate fixtures/text_input_fixture.h. The C gate checks
every codepoint position against the frozen independent classification digest.
Python is a fixture-generation tool; make test-text-input uses C and shell only.
"""
import argparse
from pathlib import Path
import unicodedata


def fixture():
    if unicodedata.unidata_version != "15.0.0":
        raise SystemExit("fixture generation requires Unicode 15.0.0")
    digest = 14695981039346656037
    count = 0
    for cp in range(0x110000):
        result = -1 if 0xD800 <= cp <= 0xDFFF else int(chr(cp).isalnum())
        count += result == 1
        digest = ((digest ^ (result + 1)) * 1099511628211) & ((1 << 64) - 1)
    points = [0, 9, 32, 48, 57, 58, 65, 90, 95, 97, 122, 127, 0xB2, 0xBC,
              0xE9, 0x300, 0x345, 0x3A3, 0x5D0, 0x5B0, 0x660, 0x6F9,
              0x905, 0x903, 0x0966, 0x2160, 0x2185, 0x3007, 0x4E00,
              0xA670, 0xD7FF, 0xD800, 0xDFFF, 0xE000, 0xFF10, 0xFF21,
              0x10400, 0x10D30, 0x11F02, 0x11F50, 0x1D400, 0x1D7CE,
              0x1E4D0, 0x1E4F0, 0x1F600, 0x2EBE0, 0x31350, 0x323AF,
              0x10FFFF]
    lines = ["/* Generated by text_input_reference.py; Python 3.12, Unicode 15.0.0. */",
             f"#define INPUT_ALNUM_FNV UINT64_C({digest})",
             f"#define INPUT_ALNUM_COUNT {count}",
             "static const struct { int cp, expected; } input_alnum_cases[] = {"]
    for cp in points:
        result = -1 if 0xD800 <= cp <= 0xDFFF else int(chr(cp).isalnum())
        lines.append(f"    {{0x{cp:X}, {result}}},")
    lines += ["};", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    path = Path(__file__).parent / "fixtures/text_input_fixture.h"
    result = fixture()
    if args.write:
        path.write_text(result)
    elif path.read_text() != result:
        raise SystemExit("text input fixture differs from Python Unicode 15")
    print("Unicode 15 input reference: 1,114,112 positions agree")
